# Generated by Django 3.1.7 on 2022-02-10 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20220210_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='img',
        ),
    ]
